// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// meanC
double meanC(NumericVector x);
RcppExport SEXP _mclm_meanC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(meanC(x));
    return rcpp_result_gen;
END_RCPP
}
// test1
NumericVector test1(NumericVector x);
RcppExport SEXP _mclm_test1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(test1(x));
    return rcpp_result_gen;
END_RCPP
}
// skipgramsC_orig
NumericMatrix skipgramsC_orig(int x_len, int ngram_size, int max_skip);
RcppExport SEXP _mclm_skipgramsC_orig(SEXP x_lenSEXP, SEXP ngram_sizeSEXP, SEXP max_skipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x_len(x_lenSEXP);
    Rcpp::traits::input_parameter< int >::type ngram_size(ngram_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_skip(max_skipSEXP);
    rcpp_result_gen = Rcpp::wrap(skipgramsC_orig(x_len, ngram_size, max_skip));
    return rcpp_result_gen;
END_RCPP
}
// skipgramsC
CharacterVector skipgramsC(CharacterVector x, int ngram_size, int max_skip, CharacterVector sep);
RcppExport SEXP _mclm_skipgramsC(SEXP xSEXP, SEXP ngram_sizeSEXP, SEXP max_skipSEXP, SEXP sepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type ngram_size(ngram_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_skip(max_skipSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sep(sepSEXP);
    rcpp_result_gen = Rcpp::wrap(skipgramsC(x, ngram_size, max_skip, sep));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mclm_meanC", (DL_FUNC) &_mclm_meanC, 1},
    {"_mclm_test1", (DL_FUNC) &_mclm_test1, 1},
    {"_mclm_skipgramsC_orig", (DL_FUNC) &_mclm_skipgramsC_orig, 3},
    {"_mclm_skipgramsC", (DL_FUNC) &_mclm_skipgramsC, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_mclm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
